name: toolchain-aarch64
on:
  workflow_dispatch:
    inputs:
      tg_disabled:
        type: boolean
        description: 'Disable Telegram notifications'
        required: false
        default: false
      tg_scratch:
        type: boolean
        description: 'Use TG scratch channel'
        required: false
        default: false
      latest_only:
        type: boolean
        description: 'Only build latest default toolchain'
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: 'Debug: Generate dummy image files'
        required: false
        default: false

env:
  BR2_DL_DIR: ~/dl
  FORCE_UNSAFE_CONFIGURE: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAG_NAME: toolchain-aarch64
  TERM: linux
  TG_TOKEN: ${{secrets.TELEGRAM_TOKEN_BOT_THINGINO}}
  TG_CHANNEL: ${{secrets.TELEGRAM_CHANNEL_THINGINO_MULTI}}
  TG_TOPIC: ${{secrets.TELEGRAM_CHANNEL_THINGINO_MULTI_TOPIC_FIRMWARE}}
  TG_CHANNEL_SCRATCH: ${{secrets.TELEGRAM_CHANNEL_THINGINO_SCRATCH}}
  TZ: UTC

jobs:
  notify-begin:
    runs-on: ubuntu-24.04-arm
    outputs:
      start_time: ${{ steps.set_output.outputs.time }}
      tg_disabled: ${{ steps.set_env.outputs.tg_disabled }}
    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone ${{ env.TZ }}

      - name: Save workflow start time to ENV
        id: set_output
        run: echo "time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Configure Environment Variables
        run: |
          echo "TG_DISABLED=${{ github.event.inputs.tg_disabled || 'false' }}" >> $GITHUB_ENV
          echo "tg_disabled=${{ github.event.inputs.tg_disabled || 'false' }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "master"
          fetch-depth: "1"

      - name: Send build start notifcation via Telegram
        if: env.TG_DISABLED == 'false'
        run: |
          if [[ "${{ github.event.inputs.tg_scratch }}" == 'true' ]]; then
            TG_CHANNEL=${{ env.TG_CHANNEL_SCRATCH }}
            export TG_TOPIC=""
          fi
          .github/scripts/tg-notify.sh -s $TG_TOKEN $TG_CHANNEL $TG_TOPIC start $TAG_NAME ${{ github.run_id }} ${{ github.repository }}

  generate-matrix:
    runs-on: ubuntu-24.04-arm
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone ${{ env.TZ }}

      - name: Configure GH workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "master"
          fetch-depth: "1"

      - name: Generate toolchain matrix
        id: set-matrix
        run: |
          if [[ "${{ github.event.inputs.latest_only }}" == 'true' ]]; then
            CONFIGS=$(find configs/github -type f -name "*defconfig" | sort | sed 's|.*/\(.*\)_defconfig|\1|' | grep gcc13)
          else
            CONFIGS=$(find configs/github -type f -name "*defconfig" | sort | sed 's|.*/\(.*\)_defconfig|\1|' | grep toolchain)
          fi
          JSON_MATRIX="{\"toolchain-version\": ["
          for CONFIG in $CONFIGS; do
            JSON_MATRIX+="\"${CONFIG}\","
          done
          JSON_MATRIX="${JSON_MATRIX%,}]}"
          echo "Matrix: $JSON_MATRIX"
          echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT

  build-toolchain:
    name: ${{ matrix.toolchain-version }}
    needs: [generate-matrix, notify-begin]
    runs-on: ubuntu-24.04-arm
    outputs:
      # Feed the hash of the commit we are building into the notify-completion release-notes step
      GIT_HASH: ${{ steps.env.outputs.git_hash }}
      TAG_NAME: ${{ steps.env.outputs.tag_name }}
    defaults:
      run:
        shell: bash
    container:
      image: debian:bullseye
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Install GitHub CLI to container
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

      - name: Update package manager sources
        run: |
          apt-get update

      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends --no-install-suggests build-essential bc ccache cmake cpio curl ca-certificates file git gh locales lzop make gawk jq p7zip-full procps rsync u-boot-tools unzip wget

      - name: Set timezone
        run: |
          ln -sf /usr/share/zoneinfo/${{ env.TZ }} /etc/localtime
          echo ${{ env.TZ }} > /etc/timezone
          DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive tzdata

      - name: Generate locales
        run: |
          sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
          locale-gen en_US.UTF-8
          update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV

      - name: Setup gh workspace to container
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repository source
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: "master"
          fetch-depth: "1"

      - name: Configure environment variables
        id: env
        run: |
          echo "WEEK_NUMBER=$(date +%U)" >> $GITHUB_ENV
          echo "CURRENT_YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "TG_DISABLED=${{ github.event.inputs.tg_disabled || 'false' }}" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          echo "GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Setup cache directories
        run: |
          mkdir -p ~/.ccache
          mkdir -p ~/dl

      - name: Fetch buildroot-dl-cache release
        id: find_release
        run: |
          REPO="${{ github.repository }}"

          # First try to find tag of the release with name "buildroot-dl-cache"
          RELEASE_TAG=$(gh release list --repo "$REPO" --json name,tagName | jq -r '.[] | select(.name=="buildroot-dl-cache") | .tagName' | sort -r | head -1 || echo "")

          # If not found, try to find tag starting with "update_cache"
          if [ -z "$RELEASE_TAG" ]; then
            echo "Could not find release with name 'buildroot-dl-cache', trying tags starting with 'update_cache'"
            RELEASE_TAG=$(gh release list --repo "$REPO" --json tagName | jq -r '.[] | select(.tagName | startswith("update_cache")) | .tagName' | head -n 1 || echo "")
          fi

          # If we found a release, mark as successful
          if [ -n "$RELEASE_TAG" ]; then
            echo "Found release with tag: $RELEASE_TAG"
            echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
            echo "release_found=true" >> $GITHUB_OUTPUT
          else
            echo "Warning: Could not find appropriate release, continuing without cache"
            echo "release_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Download buildroot-dl-cache files
        id: download_cache
        if: steps.find_release.outputs.release_found == 'true'
        run: |
          REPO="${{ github.repository }}"
          RELEASE_TAG="${{ steps.find_release.outputs.release_tag }}"

          # Create temporary directory for downloads
          mkdir -p /tmp/dl-cache

          # Try to download all assets from the release
          echo "Downloading files from release with tag: $RELEASE_TAG"
          set +e  # Turn off exit-on-error
          gh release download "$RELEASE_TAG" --repo "$REPO" --pattern "buildroot-dl-cache*" --dir "/tmp/dl-cache"
          DOWNLOAD_EXIT_CODE=$?
          set -e  # Turn on exit-on-error again

          if [ $DOWNLOAD_EXIT_CODE -ne 0 ]; then
            echo "Warning: gh command exited with code $DOWNLOAD_EXIT_CODE."
            echo "download_succeeded=false" >> $GITHUB_OUTPUT
          elif [ ! "$(ls -A /tmp/dl-cache/)" ]; then
            echo "Warning: Download directory is empty, no files were downloaded."
            echo "download_succeeded=false" >> $GITHUB_OUTPUT
          else
            echo "Download successful!"
            echo "download_succeeded=true" >> $GITHUB_OUTPUT
          fi

          # List downloaded files
          echo "Downloaded files:"
          ls -la /tmp/dl-cache/ || echo "No files found."

      - name: Extract buildroot-dl-cache
        if: steps.download_cache.outputs.download_succeeded == 'true'
        run: |
          # If there are split ZIP files, we need to ensure they're processed correctly
          if ls /tmp/dl-cache/buildroot-dl-cache.zip.* &>/dev/null; then
            # For split ZIP files, we need to extract from the first part
            echo "Extracting split ZIP files..."
            cd ~
            7z x /tmp/dl-cache/buildroot-dl-cache.zip.001 -y
          else
            # For single ZIP file
            echo "Extracting single ZIP file..."
            cd ~
            7z x /tmp/dl-cache/buildroot-dl-cache.zip -y
          fi

          # If files were extracted to a subdirectory called 'dl', move them up
          if [ -d ~/dl/dl ]; then
            echo "Moving files from ~/dl/dl to ~/dl"
            mv ~/dl/dl/* ~/dl/
            rm -rf ~/dl/dl
          fi

          # Verify extraction
          echo "Verifying extraction:"
          ls -la ~/dl/
          echo "Number of files in ~/dl:"
          find ~/dl -type f | wc -l
          echo "DL cache restored successfully"

      - name: Prepare buildroot cache
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        run: |
          BOARD=${{ matrix.toolchain-version }} GROUP=github make source WORKFLOW=1
          TIME=$(date -d @${SECONDS} +%M:%S)
          echo "TIME=${TIME}" >> ${GITHUB_ENV}

      - name: Build toolchain
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        run: |
          BOARD=${{ matrix.toolchain-version }} GROUP=github make sdk WORKFLOW=1

      - name: Generate debug dummy toolchain for workflow testing
        if: ${{ github.event.inputs.debug_enabled == 'true' }}
        run: |
          DYNAMIC_PART="${{ matrix.toolchain-version }}"
          mkdir -p ${HOME}/output/${DYNAMIC_PART}/images/
          echo "debug" > ${HOME}/output/${DYNAMIC_PART}/images/mipsel-thingino-linux-dummy_sdk-buildroot.tar.gz
          echo "TIME=7:77" >> ${GITHUB_ENV}

      - name: Rename toolchain package for release
        run: |
          INGTC=$(find ${HOME}/output/${{ matrix.toolchain-version }}*/images/ -name "mipsel-thingino-linux-*_sdk-buildroot.tar.gz" | head -n 1)
          if [[ -n "$INGTC" ]]; then
            DIR_PATH=$(dirname "$INGTC")
            TOOLCHAIN_VERSION="${{ matrix.toolchain-version }}"
            CLEAN_VERSION=${TOOLCHAIN_VERSION#toolchain_}
            INGTC_FINAL="${DIR_PATH}/thingino-toolchain-aarch64_${CLEAN_VERSION}-linux-mipsel.tar.gz"
            mv "$INGTC" "$INGTC_FINAL"
            echo "INGTC=$INGTC_FINAL" >> $GITHUB_ENV
          else
            echo "Matching file not found."
            exit 1
          fi

      - name: Upload toolchain artifact
        uses: actions/upload-artifact@v4
        with:
          name: thingino-toolchain_aarch64_${{ matrix.toolchain-version }}-linux-mipsel.tar.gz
          path: ${{ env.INGTC }}

      - name: Upload toolchain to release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2.1.0
        with:
          make_latest: false
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.INGTC }}


      - name: Send firmware completion notifications
        if: ${{ env.TG_DISABLED == 'false' && (env.INGTC) }}
        run: |
          if [[ "${{ github.event.inputs.tg_scratch }}" == 'true' ]]; then
            TG_CHANNEL=${{ env.TG_CHANNEL_SCRATCH }}
            export TG_TOPIC=""
          fi
          if [ -n "${{ env.INGTC  }}" ]; then
          .github/scripts/tg-notify.sh -s $TG_TOKEN $TG_CHANNEL $TG_TOPIC completed $TAG_NAME ${{ github.run_id }} ${{ github.repository }} ${GIT_HASH} ${GIT_BRANCH} ${TAG_NAME} ${TIME} ${{ matrix.toolchain-version }}
          fi

      - name: Send error notification
        if: ${{ env.TG_DISABLED == 'false' && failure() }}
        run: |
          if [[ "${{ github.event.inputs.tg_scratch }}" == 'true' ]]; then
            TG_CHANNEL=${{ env.TG_CHANNEL_SCRATCH }}
            export TG_TOPIC=""
          fi
          .github/scripts/tg-notify.sh -s $TG_TOKEN $TG_CHANNEL $TG_TOPIC error $TAG_NAME "CI Failed!" ${{ github.run_id }} ${{ matrix.toolchain-version }} ${{ github.repository }}

  notify-completion:
    needs: [build-toolchain, notify-begin]
    runs-on: ubuntu-24.04-arm
    if: always()
    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone ${{ env.TZ }}

      - name: Configure Environment
        run: |
          echo "TG_DISABLED=${{ github.event.inputs.tg_disabled || 'false' }}" >> $GITHUB_ENV
          echo "GIT_HASH=${{ needs.build-toolchain.outputs.git_hash }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ needs.build-toolchain.outputs.tag_name }}" >> $GITHUB_ENV

      - name: Checkout repository source
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          ref: "master"

      - name: Send notify completion summary
        if: ${{ env.TG_DISABLED == 'false' }}
        run: |
          if [[ "${{ github.event.inputs.tg_scratch }}" == 'true' ]]; then
            TG_CHANNEL=${{ env.TG_CHANNEL_SCRATCH }}
            export TG_TOPIC=""
          fi
          START_TIME=${{ needs.notify-begin.outputs.start_time }}
          END_TIME=$(date -u +%s)
          ELAPSED=$((END_TIME - START_TIME))
          ELAPSED_MIN=$((ELAPSED / 60))
          ELAPSED_SEC=$((ELAPSED % 60))
          .github/scripts/tg-notify.sh -s $TG_TOKEN $TG_CHANNEL $TG_TOPIC finish ${{ github.workflow }} "${ELAPSED_MIN}m ${ELAPSED_SEC}s" ${{ github.run_id }} ${{ github.repository }}
